contact_links:
  - name: Usage question & discussion
    url: https://github.com/Marcono1234/known-sites-extension/discussions
    about: Ask usage questions and discuss the 'known-sites-extension' in GitHub Discussions.
