name: Build extension
on:
  push:
    branches-ignore:
      # Ignore Dependabot branches because it will also open a pull request, which would cause the
      # workflow to redundantly run twice
      - dependabot/**
  pull_request:
  # Support manually running workflow, in which case the web-extension artifact is uploaded (see below)
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Package
        run: npm run package
      # Lint after building package to first compile all files
      - name: Lint extension
        run: npm run lint-web-ext

      - name: Upload extension artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        # Only upload artifact if workflow was manually triggered
        if: github.event_name == 'workflow_dispatch'
        with:
          name: web-extension
          path: ./web-ext-artifacts/known_sites*.zip
          # Don't wrap extension ZIP file in another ZIP file
          archive: false
          if-no-files-found: error
